name: "ğŸ–¥ï¸ ğŸ§ª Jobs Dashboard Tests"

on: [pull_request]

jobs:
  jobs-dashboard-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - name: Run unit tests
        run: |
          cd apps/jobs-dashboard
          pnpm test:unit

  jobs-dashboard-page-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - name: Run page tests
        run: |
          cd apps/jobs-dashboard
          pnpm test:page
